Enable layout tests for generated bindings

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,11 +43,16 @@ jobs:
       - name: Check formatting
         run: cargo fmt --all --verbose -- --check
 
+      # We always run the next two steps, so that even if formatting fails we
+      # still get compilation errors for the same run (mainly for matchers).
+
       - name: Cargo check ctru-sys (without tests)
         run: cargo 3ds clippy --package ctru-sys --color=always --verbose
+        if: success() || failure()
 
       - name: Cargo check ctru-rs (including tests)
         run: cargo 3ds clippy --package ctru-rs --color=always --verbose --all-targets
+        if: success() || failure()
 
   test:
     strategy:
